package fr.inria.corese.w3c.junit.dynamic.executor.impl;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import fr.inria.corese.core.next.data.RdfCanonicalization;
import fr.inria.corese.core.next.data.api.io.format.RDFFormat;
import fr.inria.corese.core.next.data.api.io.parser.RDFParser;
import fr.inria.corese.core.next.data.api.model.Model;
import fr.inria.corese.w3c.junit.dynamic.executor.InfrastructureException;
import fr.inria.corese.w3c.junit.dynamic.executor.TestExecutor;
import fr.inria.corese.w3c.junit.dynamic.model.W3cTestCase;
import fr.inria.corese.w3c.junit.dynamic.utils.RDFTestUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Objects;

/**
 * Executor for RDF Canonicalization tests related to blank node mapping (RDFC10MapTest).
 * Uses Corese's {@link RdfCanonicalization#canonicalMap(Model, RdfCanonicalization.HashAlgorithm)}
 * to compute the canonical blank node identifier mapping and asserts exact 1:1 match with
 * the official W3C expected mapping.
 */
public class RdfCanonicalMapTestExecutor implements TestExecutor {

    private static final Logger logger = LoggerFactory.getLogger(RdfCanonicalMapTestExecutor.class);
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    @Override
    public void execute(W3cTestCase testCase) throws Exception {
        String testName = testCase.getName();

        try {
            // Resolve file paths for action and expected result
            String actionFilePath = resolveFile(testCase.getActionFileUri());
            String resultFilePath = resolveFile(testCase.getResultFileUri());

            // Load expected mapping from JSON result file
            Map<String, String> expectedMapping = loadMappingFromFile(resultFilePath);

            // Load input model
            Model actionModel = loadModelFromFile(actionFilePath);

            // Determine hash algorithm strictly from manifest property rdfc:hashAlgorithm (default to SHA-256)
            String hashAlgoProp = testCase.getProperty(W3cTestCase.Property.HASH_ALGORITHM, String.class);
            RdfCanonicalization.HashAlgorithm algorithm = RDFTestUtils.resolveRdfcHashAlgorithm(hashAlgoProp);

            // Compute canonical mapping using Corese RDFC-1.0 algorithm
            Map<String, String> generatedMapping = RdfCanonicalization.canonicalMap(actionModel, algorithm);

            // Assert exact mapping equality
            validateMappings(generatedMapping, expectedMapping, testName);

        } catch (InfrastructureException | AssertionError e) {
            throw e;
        } catch (Exception e) {
            String errorMsg = String.format("""
                            RDF Canonical map test FAILED.
                             Test: %s
                            Action: %s
                            Result: %s
                            Error: %s""",
                    testName,
                    testCase.getActionFileUri(),
                    testCase.getResultFileUri(),
                    e.getMessage());
            logger.error(errorMsg, e);
            throw new AssertionError(errorMsg, e);
        }
    }

    private Model loadModelFromFile(String filePath) throws IOException {
        Model model = RDFTestUtils.createModel();
        RDFParser parser = RDFTestUtils.createParser(RDFFormat.NQUADS, model);
        try (FileReader reader = new FileReader(filePath)) {
            parser.parse(reader);
        }
        return model;
    }

    private Map<String, String> loadMappingFromFile(String filePath) throws IOException {
        String content = Files.readString(Path.of(filePath));
        return OBJECT_MAPPER.readValue(content, new TypeReference<Map<String, String>>() {});
    }

    private void validateMappings(Map<String, String> generated, Map<String, String> expected, String testName) {
        if (!Objects.equals(generated, expected)) {
            String msg = String.format(
                    "RDF Canonical map mismatch for test %s.%nExpected: %s%nGenerated by Corese: %s",
                    testName, expected, generated);
            logger.error(msg);
            throw new AssertionError(msg);
        }
        logger.debug("✓ Canonical map test passed for {}: {}", testName, generated);
    }

    private String resolveFile(URI uri) {
        return RDFTestUtils.loadFile(uri);
    }
}
