package fr.inria.corese.w3c.rdf11ntriples;

import fr.inria.corese.core.load.LoadException;
import fr.inria.corese.core.next.api.Model;
import fr.inria.corese.core.next.api.ValueFactory;
import fr.inria.corese.core.next.api.base.io.RDFFormat;
import fr.inria.corese.core.next.api.io.parser.RDFParser;
import fr.inria.corese.core.next.impl.exception.ParsingErrorException;
import fr.inria.corese.core.next.impl.io.parser.ParserFactory;
import fr.inria.corese.core.next.impl.temp.CoreseAdaptedValueFactory;
import fr.inria.corese.core.next.impl.temp.CoreseModel;
import fr.inria.corese.w3c.junit.w3ctests.TestFileManager;
import fr.inria.corese.w3c.junit.w3ctests.TestUtils;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.security.NoSuchAlgorithmException;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Auto-generated JUnit test file for the W3C test suite: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/manifest.ttl
 * This file was automatically generated by JUnitTestFileGenerator.java.
 * Generation date: 2025-08-11, Time: 10:33:48 Europe/Paris
 */
public class rdf11ntriplesTest {

    private static final String TEST_REPORT_FILE = Paths.get(System.getProperty("user.dir")).resolve("test/java/fr/inria/corese/w3c/rdf11ntriples/testReport.csv").toString();
    private static final String MANIFEST_URI = "https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/manifest";
    private static final String EARL = "http://www.w3.org/ns/earl#";

    /**
     * Writes the test report to the file testReport.csv.
     *
     * @param testName The name of the test.
     * @param success  The status of the test.
     */
    private void writeTestReport(String testName, String success) {
        try {
            Path testReportPath = Paths.get(TEST_REPORT_FILE);
            Files.createDirectories(testReportPath.getParent());
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX");
            Files.write(testReportPath, (MANIFEST_URI + "#" + testName + "," + dtf.format(ZonedDateTime.now()) + "," + EARL + success + "\n").getBytes(), StandardOpenOption.APPEND, StandardOpenOption.CREATE);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @AfterEach
    void afterEach(TestInfo testInfo) {
        if (testInfo.getTags().contains("skipped")) {
            writeTestReport(testInfo.getDisplayName(), "untested");
        } else {
            writeTestReport(testInfo.getDisplayName(), "passed"); // Cannot detect failure directly
        }
    }

    @BeforeAll
    static void createTestReportFile() {
        try {
            Path testReportPath = Paths.get(TEST_REPORT_FILE);
            Files.createDirectories(testReportPath.getParent());
            Files.write(testReportPath, "".getBytes());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // comment_following_triple
    // Tests comments after a triple
    @Test
    public void rdf11rdfntriplesmanifestttlcomment_following_triplecomment_following_triple() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/comment_following_triple.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "Tests comments after a triple. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/comment_following_triple.nt");
    }

    // langtagged_string
    // langtagged string 'quote'x'quote'@en
    @Test
    public void rdf11rdfntriplesmanifestttllangtagged_stringlangtagged_string() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/langtagged_string.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "langtagged string 'quote'x'quote'@en. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/langtagged_string.nt");
    }

    // lantag_with_subtag
    // lantag with subtag 'quote'x'quote'@en-us
    @Test
    public void rdf11rdfntriplesmanifestttllantag_with_subtaglantag_with_subtag() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/lantag_with_subtag.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "lantag with subtag 'quote'x'quote'@en-us. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/lantag_with_subtag.nt");
    }

    // literal
    // literal 'quote''quote''quote'x'quote''quote''quote'
    @Test
    public void rdf11rdfntriplesmanifestttlliteralliteral() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal 'quote''quote''quote'x'quote''quote''quote'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal.nt");
    }

    // literal_all_controls
    // literal_all_controls ''slash'x00'slash'x01'slash'x02'slash'x03'slash'x04...'
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_all_controlsliteral_all_controls() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_all_controls.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal_all_controls ''slash'x00'slash'x01'slash'x02'slash'x03'slash'x04...'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_all_controls.nt");
    }

    // literal_all_punctuation
    // literal_all_punctuation '!'quote'#$%&()...'
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_all_punctuationliteral_all_punctuation() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_all_punctuation.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal_all_punctuation '!'quote'#$%&()...'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_all_punctuation.nt");
    }

    // literal_ascii_boundaries
    // literal_ascii_boundaries ''slash'x00'slash'x26'slash'x28...'
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_ascii_boundariesliteral_ascii_boundaries() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_ascii_boundaries.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal_ascii_boundaries ''slash'x00'slash'x26'slash'x28...'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_ascii_boundaries.nt");
    }

    // literal_with_2_dquotes
    // literal with 2 dquotes 'quote''quote''quote'a'quote''quote'b'quote''quote''quote'
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_2_dquotesliteral_with_2_dquotes() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_2_dquotes.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with 2 dquotes 'quote''quote''quote'a'quote''quote'b'quote''quote''quote'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_2_dquotes.nt");
    }

    // literal_with_2_squotes
    // literal with 2 squotes 'quote'x''y'quote'
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_2_squotesliteral_with_2_squotes() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_2_squotes.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with 2 squotes 'quote'x''y'quote'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_2_squotes.nt");
    }

    // literal_with_BACKSPACE
    // literal with BACKSPACE
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_backspaceliteral_with_backspace() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_BACKSPACE.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with BACKSPACE. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_BACKSPACE.nt");
    }

    // literal_with_CARRIAGE_RETURN
    // literal with CARRIAGE RETURN
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_carriage_returnliteral_with_carriage_return() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_CARRIAGE_RETURN.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with CARRIAGE RETURN. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_CARRIAGE_RETURN.nt");
    }

    // literal_with_CHARACTER_TABULATION
    // literal with CHARACTER TABULATION
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_character_tabulationliteral_with_character_tabulation() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_CHARACTER_TABULATION.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with CHARACTER TABULATION. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_CHARACTER_TABULATION.nt");
    }

    // literal_with_FORM_FEED
    // literal with FORM FEED
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_form_feedliteral_with_form_feed() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_FORM_FEED.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with FORM FEED. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_FORM_FEED.nt");
    }

    // literal_with_LINE_FEED
    // literal with LINE FEED
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_line_feedliteral_with_line_feed() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_LINE_FEED.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with LINE FEED. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_LINE_FEED.nt");
    }

    // literal_with_REVERSE_SOLIDUS
    // literal with REVERSE SOLIDUS
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_reverse_solidusliteral_with_reverse_solidus() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_REVERSE_SOLIDUS.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with REVERSE SOLIDUS. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_REVERSE_SOLIDUS.nt");
    }

    // literal_with_REVERSE_SOLIDUS2
    // REVERSE SOLIDUS at end of literal
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_reverse_solidus2literal_with_reverse_solidus2() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_REVERSE_SOLIDUS2.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "REVERSE SOLIDUS at end of literal. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_REVERSE_SOLIDUS2.nt");
    }

    // literal_with_UTF8_boundaries
    // literal_with_UTF8_boundaries ''slash'x80'slash'x7ff'slash'x800'slash'xfff...'
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_utf8_boundariesliteral_with_utf8_boundaries() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_UTF8_boundaries.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal_with_UTF8_boundaries ''slash'x80'slash'x7ff'slash'x800'slash'xfff...'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_UTF8_boundaries.nt");
    }

    // literal_with_dquote
    // literal with dquote 'quote'x'quote'y'quote'
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_dquoteliteral_with_dquote() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_dquote.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with dquote 'quote'x'quote'y'quote'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_dquote.nt");
    }

    // literal_with_numeric_escape4
    // literal with numeric escape4 'slash'u
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_numeric_escape4literal_with_numeric_escape4() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_numeric_escape4.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with numeric escape4 'slash'u. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_numeric_escape4.nt");
    }

    // literal_with_numeric_escape8
    // literal with numeric escape8 'slash'u
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_numeric_escape8literal_with_numeric_escape8() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_numeric_escape8.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with numeric escape8 'slash'u. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_numeric_escape8.nt");
    }

    // literal_with_squote
    // literal with squote 'quote'x'y'quote'
    @Test
    public void rdf11rdfntriplesmanifestttlliteral_with_squoteliteral_with_squote() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_squote.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "literal with squote 'quote'x'y'quote'. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/literal_with_squote.nt");
    }

    // minimal_whitespace
    // tests absense of whitespace between subject, predicate, object and end-of-statement
    @Test
    public void rdf11rdfntriplesmanifestttlminimal_whitespaceminimal_whitespace() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/minimal_whitespace.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "tests absense of whitespace between subject, predicate, object and end-of-statement. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/minimal_whitespace.nt");
    }

    // nt-syntax-bad-base-01
    // @base not allowed in N-Triples (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadbase01ntsyntaxbadbase01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-base-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "@base not allowed in N-Triples (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-base-01.nt"
        );
    }

    // nt-syntax-bad-bnode-01
    // Colon in bnode label not allowed (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadbnode01ntsyntaxbadbnode01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-bnode-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Colon in bnode label not allowed (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-bnode-01.nt"
        );
    }

    // nt-syntax-bad-bnode-02
    // Colon in bnode label not allowed (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadbnode02ntsyntaxbadbnode02() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-bnode-02.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Colon in bnode label not allowed (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-bnode-02.nt"
        );
    }

    // nt-syntax-bad-esc-01
    // Bad string escape (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadesc01ntsyntaxbadesc01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-esc-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad string escape (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-esc-01.nt"
        );
    }

    // nt-syntax-bad-esc-02
    // Bad string escape (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadesc02ntsyntaxbadesc02() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-esc-02.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad string escape (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-esc-02.nt"
        );
    }

    // nt-syntax-bad-esc-03
    // Bad string escape (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadesc03ntsyntaxbadesc03() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-esc-03.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad string escape (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-esc-03.nt"
        );
    }

    // nt-syntax-bad-lang-01
    // langString with bad lang (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadlang01ntsyntaxbadlang01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-lang-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "langString with bad lang (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-lang-01.nt"
        );
    }

    // nt-syntax-bad-num-01
    // no numbers in N-Triples (integer) (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadnum01ntsyntaxbadnum01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-num-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "no numbers in N-Triples (integer) (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-num-01.nt"
        );
    }

    // nt-syntax-bad-num-02
    // no numbers in N-Triples (decimal) (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadnum02ntsyntaxbadnum02() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-num-02.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "no numbers in N-Triples (decimal) (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-num-02.nt"
        );
    }

    // nt-syntax-bad-num-03
    // no numbers in N-Triples (float) (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadnum03ntsyntaxbadnum03() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-num-03.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "no numbers in N-Triples (float) (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-num-03.nt"
        );
    }

    // nt-syntax-bad-prefix-01
    // @prefix not allowed in n-triples (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadprefix01ntsyntaxbadprefix01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-prefix-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "@prefix not allowed in n-triples (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-prefix-01.nt"
        );
    }

    // nt-syntax-bad-string-01
    // mismatching string literal open/close (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstring01ntsyntaxbadstring01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "mismatching string literal open/close (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-01.nt"
        );
    }

    // nt-syntax-bad-string-02
    // mismatching string literal open/close (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstring02ntsyntaxbadstring02() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-02.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "mismatching string literal open/close (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-02.nt"
        );
    }

    // nt-syntax-bad-string-03
    // single quotes (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstring03ntsyntaxbadstring03() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-03.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "single quotes (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-03.nt"
        );
    }

    // nt-syntax-bad-string-04
    // long single string literal (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstring04ntsyntaxbadstring04() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-04.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "long single string literal (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-04.nt"
        );
    }

    // nt-syntax-bad-string-05
    // long double string literal (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstring05ntsyntaxbadstring05() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-05.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "long double string literal (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-05.nt"
        );
    }

    // nt-syntax-bad-string-06
    // string literal with no end (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstring06ntsyntaxbadstring06() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-06.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "string literal with no end (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-06.nt"
        );
    }

    // nt-syntax-bad-string-07
    // string literal with no start (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstring07ntsyntaxbadstring07() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-07.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "string literal with no start (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-string-07.nt"
        );
    }

    // nt-syntax-bad-struct-01
    // N-Triples does not have objectList (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstruct01ntsyntaxbadstruct01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-struct-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "N-Triples does not have objectList (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-struct-01.nt"
        );
    }

    // nt-syntax-bad-struct-02
    // N-Triples does not have predicateObjectList (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbadstruct02ntsyntaxbadstruct02() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-struct-02.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "N-Triples does not have predicateObjectList (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-struct-02.nt"
        );
    }

    // nt-syntax-bad-uri-01
    // Bad IRI : space (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri01ntsyntaxbaduri01() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-01.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : space (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-01.nt"
        );
    }

    // nt-syntax-bad-uri-02
    // Bad IRI : bad escape (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri02ntsyntaxbaduri02() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-02.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : bad escape (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-02.nt"
        );
    }

    // nt-syntax-bad-uri-03
    // Bad IRI : bad long escape (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri03ntsyntaxbaduri03() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-03.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : bad long escape (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-03.nt"
        );
    }

    // nt-syntax-bad-uri-04
    // Bad IRI : character escapes not allowed (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri04ntsyntaxbaduri04() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-04.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : character escapes not allowed (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-04.nt"
        );
    }

    // nt-syntax-bad-uri-05
    // Bad IRI : character escapes not allowed (2) (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri05ntsyntaxbaduri05() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-05.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : character escapes not allowed (2) (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-05.nt"
        );
    }

    // nt-syntax-bad-uri-06
    // Bad IRI : relative IRI not allowed in subject (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri06ntsyntaxbaduri06() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-06.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : relative IRI not allowed in subject (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-06.nt"
        );
    }

    // nt-syntax-bad-uri-07
    // Bad IRI : relative IRI not allowed in predicate (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri07ntsyntaxbaduri07() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-07.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : relative IRI not allowed in predicate (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-07.nt"
        );
    }

    // nt-syntax-bad-uri-08
    // Bad IRI : relative IRI not allowed in object (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri08ntsyntaxbaduri08() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-08.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : relative IRI not allowed in object (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-08.nt"
        );
    }

    // nt-syntax-bad-uri-09
    // Bad IRI : relative IRI not allowed in datatype (negative test)
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbaduri09ntsyntaxbaduri09() {
        // Load action file
        assertThrows(ParsingErrorException.class, () -> {
                    RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
                    ParserFactory parserFactory = new ParserFactory();
                    ValueFactory valueFactory = new CoreseAdaptedValueFactory();
                    Model model = new CoreseModel();
                    String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-09.nt")).toString();
                    FileReader reader = new FileReader(localFilePath);
                    RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
                    parser.parse(reader);
                }, "Bad IRI : relative IRI not allowed in datatype (negative test). Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bad-uri-09.nt"
        );
    }

    // nt-syntax-bnode-01
    // bnode subject
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbnode01ntsyntaxbnode01() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bnode-01.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "bnode subject. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bnode-01.nt");
    }

    // nt-syntax-bnode-02
    // bnode object
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbnode02ntsyntaxbnode02() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bnode-02.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "bnode object. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bnode-02.nt");
    }

    // nt-syntax-bnode-03
    // Blank node labels may start with a digit
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxbnode03ntsyntaxbnode03() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bnode-03.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "Blank node labels may start with a digit. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-bnode-03.nt");
    }

    // nt-syntax-datatypes-01
    // xsd:byte literal
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxdatatypes01ntsyntaxdatatypes01() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-datatypes-01.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "xsd:byte literal. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-datatypes-01.nt");
    }

    // nt-syntax-datatypes-02
    // integer as xsd:string
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxdatatypes02ntsyntaxdatatypes02() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-datatypes-02.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "integer as xsd:string. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-datatypes-02.nt");
    }

    // nt-syntax-file-01
    // Empty file
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxfile01ntsyntaxfile01() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-file-01.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "Empty file. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-file-01.nt");
    }

    // nt-syntax-file-02
    // Only comment
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxfile02ntsyntaxfile02() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-file-02.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "Only comment. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-file-02.nt");
    }

    // nt-syntax-file-03
    // One comment, one empty line
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxfile03ntsyntaxfile03() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-file-03.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "One comment, one empty line. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-file-03.nt");
    }

    // nt-syntax-str-esc-01
    // string literal with escaped newline
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxstresc01ntsyntaxstresc01() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-str-esc-01.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "string literal with escaped newline. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-str-esc-01.nt");
    }

    // nt-syntax-str-esc-02
    // string literal with Unicode escape
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxstresc02ntsyntaxstresc02() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-str-esc-02.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "string literal with Unicode escape. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-str-esc-02.nt");
    }

    // nt-syntax-str-esc-03
    // string literal with long Unicode escape
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxstresc03ntsyntaxstresc03() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-str-esc-03.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "string literal with long Unicode escape. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-str-esc-03.nt");
    }

    // nt-syntax-string-01
    // string literal
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxstring01ntsyntaxstring01() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-string-01.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "string literal. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-string-01.nt");
    }

    // nt-syntax-string-02
    // langString literal
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxstring02ntsyntaxstring02() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-string-02.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "langString literal. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-string-02.nt");
    }

    // nt-syntax-string-03
    // langString literal with region
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxstring03ntsyntaxstring03() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-string-03.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "langString literal with region. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-string-03.nt");
    }

    // nt-syntax-subm-01
    // Submission test from Original RDF Test Cases
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxsubm01ntsyntaxsubm01() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-subm-01.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "Submission test from Original RDF Test Cases. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-subm-01.nt");
    }

    // nt-syntax-uri-01
    // Only IRIs
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxuri01ntsyntaxuri01() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-uri-01.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "Only IRIs. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-uri-01.nt");
    }

    // nt-syntax-uri-02
    // IRIs with Unicode escape
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxuri02ntsyntaxuri02() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-uri-02.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "IRIs with Unicode escape. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-uri-02.nt");
    }

    // nt-syntax-uri-03
    // IRIs with long Unicode escape
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxuri03ntsyntaxuri03() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-uri-03.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "IRIs with long Unicode escape. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-uri-03.nt");
    }

    // nt-syntax-uri-04
    // Legal IRIs
    @Test
    public void rdf11rdfntriplesmanifestttlntsyntaxuri04ntsyntaxuri04() throws IOException, NoSuchAlgorithmException, InterruptedException {
        // Load action file
        RDFFormat format = TestUtils.commandStringFormatToRDFFormat("ntriples");
        ParserFactory parserFactory = new ParserFactory();
        ValueFactory valueFactory = new CoreseAdaptedValueFactory();
        Model model = new CoreseModel();
        String localFilePath = TestFileManager.getLocalFilePath(URI.create("https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-uri-04.nt")).toString();
        RDFParser parser = parserFactory.createRDFParser(format, model, valueFactory);
        FileReader reader = new FileReader(localFilePath);
        parser.parse(reader);
        assertTrue(true, "Legal IRIs. Test file: https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/nt-syntax-uri-04.nt");
    }

}