package fr.inria.corese.w3c.junit;

import fr.inria.corese.w3c.junit.w3ctests.IW3cTest;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Generates a JUnit test file for the W3C test suite.
 */
public class JUnitTestFileGenerator {

    private static final Logger logger = LoggerFactory.getLogger(JUnitTestFileGenerator.class);

    private final URI manifestUri;
    private final String testName;
    private final List<IW3cTest> tests;
    private final Path exportPath;


    /**
     * Constructs a new JUnitTestFileGenerator.
     *
     * @param testName The name of the test suite. This will also be used as part of the export path.
     * @param manifestUri The URI of the test manifest file.
     * @param exportPath The base directory path where the generated test file will be exported.
     * @param tests A list of {@link IW3cTest} instances to be included in this test file.
     */
    public JUnitTestFileGenerator(String testName, URI manifestUri, Path exportPath, List<IW3cTest> tests) {
        this.testName = testName;
        this.manifestUri = manifestUri;
        this.exportPath = exportPath.resolve(testName);
        this.tests = tests;
    }

    /**
     * Generates a JUnit test file for the W3C test suite.
     */
    public void generate() {

        // Initialize directories
        Path testDirectory = this.createDirectory(this.exportPath);

        // Generate file test
        String fileName = testName + "Test.java";
        Path testFile = this.generateTestFile(testDirectory, fileName);

        // Write test file
        try {
            Files.write(testFile, this.generateTestFileContent(testFile.toString(), fileName).getBytes());
            logger.info("Wrote test file: " + testFile);
        } catch (IOException e) {
            logger.error("Failed to write test file: " + testFile, e);
        }

    }

    /**
     * Creates a directory at the specified path if it does not already exist.
     * 
     * @param directoryPath The path to the directory to create.
     */
    private Path createDirectory(Path directoryPath) {
        if (!Files.exists(directoryPath)) {
            try {
                Files.createDirectories(directoryPath);
                logger.info("Created directory: " + directoryPath);
            } catch (IOException e) {
                logger.error("Failed to create directory: " + directoryPath, e);
            }
        }
        return directoryPath;
    }

    /**
     * Generates a test file at the specified path if it does not already exist.
     * 
     * @param testDirectory The directory where the test file should be generated.
     * @param fileName      The name of the test file.
     * @return The path to the test file.
     */
    private Path generateTestFile(Path testDirectory, String fileName) {
        Path filePath = testDirectory.resolve(fileName);

        if (Files.exists(filePath)) {
            return filePath;
        }

        try {
            Files.createFile(filePath);
            logger.info("Created test file: " + filePath);
        } catch (IOException e) {
            logger.error("Failed to create test file: " + filePath, e);
        }
        return filePath;
    }

    /**
     * Generates the content of the test file.
     * 
     * @param path     The path of the file.
     * @param fileName The name of the file.
     * @return The content of the test file.
     */
    private String generateTestFileContent(String path, String fileName) {
        StringBuilder content = new StringBuilder();

        // Package
        content.append(this.getPackage(path, fileName));
        content.append("\n\n");

        // Imports
        Set<String> imports = new HashSet<>();
        for (IW3cTest test : tests) {
            imports.addAll(test.getImports());
        }
        imports.addAll(this.defineImports());
        imports.stream().sorted().forEach(imp -> content.append("import ").append(imp).append(";\n"));
        content.append("\n");

        // Class comment
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        ZonedDateTime nowWithZone = ZonedDateTime.now();

        content.append("/**\n");
        content.append(" * Auto-generated JUnit test file for the W3C test suite: ");
        content.append(manifestUri);
        content.append("\n");
        content.append(" * This file was automatically generated by JUnitTestFileGenerator.java.\n");
        content.append(" * Generation date: ");
        content.append(LocalDate.now());
        content.append(", Time: ");
        content.append(nowWithZone.format(timeFormatter));
        content.append(" ");
        content.append(nowWithZone.getZone());
        content.append("\n");
        content.append(" */\n");

        // Class declaration
        content.append("public class ");
        content.append(fileName.substring(0, fileName.indexOf(".")));
        content.append(" {\n\n");

        content.append(this.generateTestLifecycleCallbacks());

        // Test methods
        for (IW3cTest test : tests) {
            content.append(test.generate());
            content.append("\n");
        }

        // End of class
        content.append("}");

        return content.toString();
    }

    /**
     * Returns the package declaration based on the given path and file name.
     * 
     * @param path     The path of the file.
     * @param fileName The name of the file.
     * @return The package declaration.
     */
    private String getPackage(String path, String fileName) {
        String normalizedPath = path.replace("\\", "/");
        int javaIndex = normalizedPath.indexOf("/java/");
        if (javaIndex == -1) {
            throw new IllegalArgumentException("Invalid path: 'java' directory not found in path: " + path);
        }
        String packagePath = normalizedPath.substring(javaIndex + 6)
                .replace("/" + fileName, "")
                .replace("/", ".");
        return "package " + packagePath + ";";
    }

    private String generateTestLifecycleCallbacks() {
        StringBuilder callbacks = new StringBuilder();
        Path relativePathToResultCsv = Paths.get(System.getProperty("user.dir")).relativize(exportPath)
                .resolve("testReport.csv");
        relativePathToResultCsv = relativePathToResultCsv.subpath(1, relativePathToResultCsv.getNameCount());
        callbacks.append("    private static final String TEST_REPORT_FILE = "
                + "Paths.get(System.getProperty(\"user.dir\")).resolve(\"" + relativePathToResultCsv.toString().replace("\\", "/")
                + "\").toString();\n");

        callbacks.append("    private static final String MANIFEST_URI = \"")
                .append(manifestUri.toString().substring(0, manifestUri.toString().lastIndexOf("."))).append("\";\n");
        callbacks.append("    private static final String EARL = \"http://www.w3.org/ns/earl#\";\n\n");

        callbacks.append("    /**\n");
        callbacks.append("     * Writes the test report to the file testReport.csv.\n");
        callbacks.append("     *\n");
        callbacks.append("     * @param testName The name of the test.\n");
        callbacks.append("     * @param success  The status of the test.\n");
        callbacks.append("     */\n");
        callbacks.append("    private void writeTestReport(String testName, String success) {\n");
        callbacks.append("        try {\n");
        callbacks.append("            Path testReportPath = Paths.get(TEST_REPORT_FILE);\n");
        callbacks.append("            Files.createDirectories(testReportPath.getParent());\n");
        callbacks.append("            DateTimeFormatter dtf = DateTimeFormatter.ofPattern(\"yyyy-MM-dd'T'HH:mm:ssXXX\");\n");
        callbacks.append("            Files.write(testReportPath, (MANIFEST_URI + \"#\" + testName + \",\" + dtf.format(ZonedDateTime.now()) + \",\" + EARL + success + \"\\n\").getBytes(), StandardOpenOption.APPEND, StandardOpenOption.CREATE);\n");

        callbacks.append("        } catch (IOException e) {\n");
        callbacks.append("            e.printStackTrace();\n");
        callbacks.append("        }\n");
        callbacks.append("    }\n\n");

        callbacks.append("    @AfterEach\n");
        callbacks.append("    void afterEach(TestInfo testInfo) {\n");
        callbacks.append("        if (testInfo.getTags().contains(\"skipped\")) {\n");
        callbacks.append("            writeTestReport(testInfo.getDisplayName(), \"untested\");\n");
        callbacks.append("        } else {\n");
        callbacks.append("            writeTestReport(testInfo.getDisplayName(), \"passed\"); // Cannot detect failure directly\n");
        callbacks.append("        }\n");
        callbacks.append("    }\n\n");

        callbacks.append("    @BeforeAll\n");
        callbacks.append("    static void createTestReportFile() {\n");
        callbacks.append("        try {\n");
        callbacks.append("            Path testReportPath = Paths.get(TEST_REPORT_FILE);\n");
        callbacks.append("            Files.createDirectories(testReportPath.getParent());\n");
        callbacks.append("            Files.write(testReportPath, \"\".getBytes());\n");
        callbacks.append("        } catch (IOException e) {\n");
        callbacks.append("            e.printStackTrace();\n");
        callbacks.append("        }\n");
        callbacks.append("    }\n\n");

        return callbacks.toString();
    }

    private Set<String> defineImports() {
        Set<String> imports = new HashSet<>();
        imports.add("fr.inria.corese.w3c.junit.w3ctests.TestUtils");
        imports.add("java.nio.file.Path");
        imports.add("java.nio.file.Paths");
        imports.add("java.nio.file.Files");
        imports.add("java.nio.file.StandardOpenOption");
        imports.add("org.junit.jupiter.api.AfterEach");
        imports.add("org.junit.jupiter.api.BeforeAll");
        imports.add("org.junit.jupiter.api.Test");
        imports.add("org.junit.jupiter.api.TestInfo");
        imports.add("org.junit.jupiter.api.Tag");
        imports.add("java.time.format.DateTimeFormatter");
        imports.add("java.time.ZonedDateTime");
        return imports;
    }
}
